### ISSUE TITLE
Deploy the contracts to Rinkeby network

### ISSUE THREAD

**Issue by ShaneRich5** [ShaneRich5/crowd-coin-contracts#8]

**Comment by ShaneRich5** [comment]
Deployed to

```
Attempting to deploy from account 0x0037020aa4b82187cdB6BFE2db5494350f2582b1
Contract deployed to 0xe272C4626B4995932Aeeb13fef6073b1896265B0
```

**Comment by ShaneRich5** [comment]
I did receive the following error:

```
/Users/shanerichards/projects/crowd-coin-contracts/node_modules/web3-provider-engine/index.js:219
    number:           ethUtil.toBuffer(jsonBlock.number),
                                                 ^
TypeError: Cannot read property 'number' of null
    at toBufferBlock (/Users/shanerichards/projects/crowd-coin-contracts/node_modules/web3-provider-engine/index.js:219:50)
    at /Users/shanerichards/projects/crowd-coin-contracts/node_modules/web3-provider-engine/index.js:60:27
    at /Users/shanerichards/projects/crowd-coin-contracts/node_modules/web3-provider-engine/index.js:136:12
    at /Users/shanerichards/projects/crowd-coin-contracts/node_modules/web3-provider-engine/index.js:199:9
    at /Users/shanerichards/projects/crowd-coin-contracts/node_modules/async/internal/once.js:12:16
    at replenish (/Users/shanerichards/projects/crowd-coin-contracts/node_modules/async/internal/eachOfLimit.js:61:25)
    at /Users/shanerichards/projects/crowd-coin-contracts/node_modules/async/internal/eachOfLimit.js:71:9
    at eachLimit (/Users/shanerichards/projects/crowd-coin-contracts/node_modules/async/eachLimit.js:43:36)
    at /Users/shanerichards/projects/crowd-coin-contracts/node_modules/async/internal/doLimit.js:9:16
    at end (/Users/shanerichards/projects/crowd-coin-contracts/node_modules/web3-provider-engine/index.js:176:5)
    at /Users/shanerichards/projects/crowd-coin-contracts/node_modules/web3-provider-engine/subproviders/provider.js:19:5
    at XMLHttpRequest.request.onreadystatechange (/Users/shanerichards/projects/crowd-coin-contracts/node_modules/web3-providers-http/src/index.js:96:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/shanerichards/projects/crowd-coin-contracts/node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
    at XMLHttpRequest._setReadyState (/Users/shanerichards/projects/crowd-coin-contracts/node_modules/xhr2-cookies/xml-http-request.ts:219:8)
    at XMLHttpRequest._onHttpResponseEnd (/Users/shanerichards/projects/crowd-coin-contracts/node_modules/xhr2-cookies/xml-http-request.ts:345:8)
    at IncomingMessage.<anonymous> (/Users/shanerichards/projects/crowd-coin-contracts/node_modules/xhr2-cookies/xml-http-request.ts:311:39)
```
